services:
  quizzed-main:
    container_name: quizzed-main
    build:
      context: .
      dockerfile: ./apps/quizzed-main/Dockerfile
      target: development
    command: npm run start:dev quizzed-main
    env_file:
      - ./apps/quizzed-main/.env
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '8000:8000'
    
  auth:
    container_name: quizzed-auth
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    env_file:
      - ./apps/auth/.env
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  
  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
      
  mongodb:
    image: mongo
    container_name: quizzed-mongo-primary
    ports:
      - "27017:27017"
    volumes:
      - mongodb_master_data:/data/db

volumes:
  mongodb_master_data:
    driver: local